{{- if and .Values.gateway.enabled .Values.gateway.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mcp-bridge.fullname" . }}-gateway
  labels:
    {{- include "mcp-bridge.gateway.labels" . | nindent 4 }}
spec:
  {{- if .Values.gateway.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.gateway.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.gateway.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mcp-bridge.gateway.selectorLabels" . | nindent 6 }}
{{- end }}