{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mcp-bridge.fullname" . }}-gateway
  labels:
    {{- include "mcp-bridge.gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mcp-bridge.gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.gateway.service.targetPort }}
        - protocol: TCP
          port: 9090
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    {{- if .Values.redis.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mcp-bridge.fullname" . }}-router
  labels:
    {{- include "mcp-bridge.router.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mcp-bridge.router.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.router.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              {{- include "mcp-bridge.gateway.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.gateway.service.port }}
  {{- end }}
{{- end }}