{{- if .Values.router.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-bridge.fullname" . }}-router
  labels:
    {{- include "mcp-bridge.router.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.router.replicaCount }}
  selector:
    matchLabels:
      {{- include "mcp-bridge.router.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/router-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "mcp-bridge.router.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-bridge.router.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: router
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "mcp-bridge.router.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config
            - /etc/mcp/config.yaml
          ports:
            - name: metrics
              containerPort: {{ .Values.router.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.router.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: MCP_GATEWAY_URL
              value: "wss://{{ include "mcp-bridge.fullname" . }}-gateway:{{ .Values.gateway.service.port }}/ws"
            - name: MCP_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-bridge.fullname" . }}-secrets
                  key: mcp-auth-token
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/mcp-router
                - health
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/mcp-router
                - health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.router.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/mcp
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "mcp-bridge.fullname" . }}-router-config
        - name: tmp
          emptyDir: {}
      {{- with .Values.router.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}