# Configuration for golangci-lint v2.x
version: 2

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    colored-line-number: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  # Error checking
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Code complexity
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 20
  cyclop:
    max-complexity: 10
  funlen:
    lines: 60
    statements: 40

  # Code style and formatting
  godot:
    scope: declarations
    capital: false
  nlreturn:
    block-size: 2
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2

  # Security
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked - covered by errcheck
  
  # Performance
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - commentedOutCode

  # Dependencies - depguard temporarily disabled due to v1.53.x configuration issues
  # See: https://github.com/golangci/golangci-lint/issues/3906

  # Constants and magic numbers
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
    
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers: "0,1,2,10,100,1000,1024"  # Only truly common numbers
    ignored-functions:
      - os.Chmod
      - os.Mkdir
      - os.MkdirAll
      - os.OpenFile

  # Line length
  lll:
    line-length: 120
    tab-width: 1

  # Variable naming
  varnamelen:
    min-name-length: 1
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - id
      - db
      - tx
      - ok
      - i
      - j
      - k

  # Testing
  testifylint:
    enable-all: true
  thelper:
    test:
      first: true
      name: true
      begin: true
    benchmark:
      first: true
      name: true
      begin: true

  # Interface design
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic

linters:
  enable:
    # Core quality (enabled by default)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Security
    - gosec
    - bidichk

    # Code complexity
    - gocyclo
    - gocognit
    - cyclop
    - funlen
    - nestif

    # Style and formatting
    - godot
    - nlreturn
    - wsl_v5
    - whitespace
    - mirror
    - tagalign

    # Performance
    - gocritic
    - prealloc
    - unconvert
    - perfsprint
    - sloglint

    # Correctness
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - makezero
    - nilerr
    - nilnil
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - tparallel

    # Dependencies and imports
    # - depguard  # Disabled due to v1.53.x configuration issues
    - importas
    # NOTE: gomoddirectives is intentionally disabled for this monorepo
    # All local replace directives (e.g., replace ../.. or ../router) are required
    # for proper monorepo functionality where services reference local packages
    # - gomoddirectives

    # Constants and literals
    - goconst
    - mnd

    # Code organization
    - decorder
    - grouper
    # - iface
    - interfacebloat

    # Naming and conventions
    - errname
    - goheader
    - goprintffuncname

    # Testing
    - testifylint
    - thelper
    - testableexamples

    # Documentation
    - godox

    # Type safety
    - ireturn
    # - recvcheck

    # Maintenance
    - maintidx
    - misspell
    - asciicheck
    - lll

    # Go-specific best practices
    - gochecknoinits
    - gocheckcompilerdirectives
    - usestdlibvars
    # - intrange  # Not available in v1.x

  disable:
    # Too strict for most projects
    - gochecknoglobals
    - gosmopolitan
    - exhaustruct
    - varnamelen
    - nonamedreturns
    - tagliatelle
    
    # Conflicts with other tools/practices
    - testpackage
    - wrapcheck
    - err113
    
    # Performance impact
    - dupl

issues:
  uniq-by-line: true
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - bin
    - dist
    - .git
    - node_modules
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"
    - ".*_gen\\.go$"
  exclude: []
  
  exclude-rules:

    # Allow some flexibility in main.go files
    - path: cmd/.*/main\.go
      linters:
        - gochecknoinits  # Main files need init functions


  max-issues-per-linter: 100
  max-same-issues: 20
  new: false

severity:
  default-severity: error
  case-sensitive: false