# Configuration for golangci-lint
run:
  timeout: 10m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - funlen
    - nestif
    - godot
    - nlreturn
    - gocritic
    - prealloc
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - makezero
    - nilerr
    - nilnil
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - goconst
    - mnd
    - decorder
    - grouper
    - interfacebloat
    - errname
    - goprintffuncname
    - testifylint
    - thelper
    - ireturn
    - maintidx
    - misspell
    - asciicheck
    - lll
    - gochecknoinits
    - usestdlibvars