# TruffleHog Configuration
# Excludes test certificates and fixtures from secret scanning

# Exclude test certificate directories and test fixtures
exclude_paths:
  # E2E test certificates (intentionally committed for testing)
  - test/e2e/full_stack/certs/
  - test/e2e/weather/certs/

  # Test fixtures with embedded test keys
  - "**/testdata/"
  - "**/*_test.go"
  - "**/test/testutil/"

  # Node modules
  - node_modules/

# Exclude specific detectors that cause false positives in test files
exclude_detectors:
  # Private keys in test files are intentional test fixtures
  # - PrivateKey  # Uncomment if needed, but path exclusions should be sufficient

# Verify findings (optional, defaults to true)
verify: true

# Only fail on verified secrets (optional)
# only_verified: true
