# Production MCP Gateway Configuration
version: 1

server:
  host: 0.0.0.0
  port: 8443
  metrics_port: 9090
  max_connections: 10000
  max_connections_per_ip: 100
  protocol: websocket
  
  # TLS Configuration
  tls:
    enabled: true
    cert_file: /etc/tls/tls.crt
    key_file: /etc/tls/tls.key
    min_version: "1.3"
    client_auth: none

# Authentication configuration
auth:
  provider: jwt
  jwt:
    issuer: mcp-gateway
    audience: mcp-services
    secret_key_env: JWT_SECRET_KEY

# Service discovery
service_discovery:
  provider: kubernetes
  kubernetes:
    in_cluster: true
    namespace_pattern: mcp-servers-*
    service_labels:
      mcp-enabled: "true"
  refresh_rate: 30s

# Routing configuration  
routing:
  strategy: least_connections
  health_check_interval: 10s
  circuit_breaker:
    failure_threshold: 5
    success_threshold: 2
    timeout: 30

# Session management configuration
sessions:
  provider: redis
  ttl: 3600      # 1 hour
  redis:
    url: ${REDIS_URL}
    pool_size: 100
    max_retries: 3

# Rate limiting configuration
rate_limit:
  enabled: true
  provider: redis
  requests_per_sec: 100
  burst: 200
  redis:
    url: ${REDIS_URL}
    pool_size: 10
    max_retries: 3

# Circuit breaker configuration
circuit_breaker:
  enabled: true
  failure_threshold: 5
  success_threshold: 2
  timeout_seconds: 30
  max_requests: 100
  interval_seconds: 60

# Metrics configuration
metrics:
  enabled: true
  endpoint: "0.0.0.0:9090"
  path: /metrics

# Logging configuration
logging:
  level: info
  format: json

# Distributed tracing
tracing:
  enabled: false
  service_name: mcp-gateway
  sampler_type: const
  sampler_param: 1.0