apiVersion: v1
kind: Secret
metadata:
  name: mcp-gateway-secrets
  namespace: mcp-system
type: Opaque
stringData:
  # JWT secret for token signing/validation
  jwt-secret-key: "CHANGE_ME_TO_A_SECURE_RANDOM_KEY"
  
  # Redis connection string for shared state
  redis-url: "redis://redis.mcp-system.svc.cluster.local:6379/0"
  
  # TLS certificate and key (base64 encoded in real deployment)
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    # Your TLS certificate here
    -----END CERTIFICATE-----
  
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    # Your TLS private key here
    -----END PRIVATE KEY-----