server:
  port: 8443
  tls:
    enabled: true
    cert_file: /etc/tls/tls.crt
    key_file: /etc/tls/tls.key
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "OPTIONS"]
    allowed_headers: ["Authorization", "Content-Type"]
  rate_limiting:
    enabled: true
    requests_per_minute: 500

auth:
  jwt:
    secret_key_env: JWT_SECRET_KEY
    expiry: 24h
  bearer:
    enabled: true

sessions:
  provider: redis
  ttl: 3600
  redis:
    url: redis://mcp-gateway-redis-master:6379
    password: PbDwuIX2EI
    db: 0
    pool_size: 10
    max_retries: 3

service_discovery:
  provider: sse
  sse:
    services:
      - name: serena-mcp
        namespace: coding-assistant
        base_url: http://serena-mcp.mcp.svc.cluster.local:8080
        stream_endpoint: /sse
        request_endpoint: /message
        weight: 100
        health_check:
          enabled: true
          interval: 30s
          timeout: 5s

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: /metrics
  health:
    enabled: true
    path: /health

logging:
  level: debug
  format: json
  correlation_id: true
