apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-gateway-config
  namespace: mcp-system
data:
  gateway.yaml: |
    version: 1
    server:
      port: 8443
      metrics_port: 9090
      max_connections: 50000
      connection_buffer_size: 65536
      protocol: both
      tcp_port: 9443
      tcp_health_port: 9444
    
    auth:
      provider: jwt
      jwt:
        issuer: "mcp-gateway.example.com"
        audience: "mcp-gateway"
        secret_key_env: JWT_SECRET_KEY
    
    routing:
      strategy: least_connections
      health_check_interval: 30s
      circuit_breaker:
        failure_threshold: 5
        success_threshold: 2
        timeout: 30s
    
    service_discovery:
      mode: kubernetes
      namespace_selector:
        - mcp-servers
      label_selector:
        mcp.bridge/enabled: "true"
    
    logging:
      level: info
      format: json
      
    metrics:
      enabled: true
      path: /metrics