global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mcp-gateway'
    static_configs:
      - targets: ['gateway:9090']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
