name: Performance Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run benchmarks daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:


jobs:
  go-version:
    uses: ./.github/workflows/_go-version.yml

  benchmark:
    runs-on: ubuntu-latest
    
    needs: go-version
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ needs.go-version.outputs.go-version }}
        
    - name: Install dependencies
      run: |
        go mod download

        # Install benchmarking tools
        go install golang.org/x/perf/cmd/benchstat@latest
        
    - name: Run Go benchmarks
      run: |
        # Run benchmarks and save results
        go test -bench=. -benchmem -benchtime=10s ./... \
          -run=^$ \
          | tee new-benchmarks.txt

        # Run CPU profiling benchmarks
        go test -bench=. -benchmem -benchtime=30s \
          -cpuprofile=cpu.prof \
          ./services/gateway/internal/... \
          -run=^$ || true
          
    - name: Compare with baseline
      if: github.event_name == 'pull_request'
      run: |
        # Fetch baseline benchmarks from main branch
        git fetch origin main
        git checkout origin/main
        
        # Run baseline benchmarks
        go test -bench=. -benchmem -benchtime=10s ./... \
          -run=^$ \
          | tee old-benchmarks.txt
          
        # Switch back to PR branch
        git checkout -
        
        # Compare results
        benchstat old-benchmarks.txt new-benchmarks.txt | tee comparison.txt
        
        # Check for significant regressions (>10% slower)
        if grep -E "\\+[0-9]{2,}\\.[0-9]+%" comparison.txt; then
          echo "::warning::Performance regression detected"
          exit 1
        fi
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: |
          new-benchmarks.txt
          old-benchmarks.txt
          comparison.txt
          cpu.prof
          
    # Benchmark storage disabled - enable when gh-pages branch is ready
    # - name: Store benchmark result
    #   if: github.ref == 'refs/heads/main'
    #   uses: benchmark-action/github-action-benchmark@v1
    #   with:
    #     name: MCP Bridge Benchmarks
    #     tool: 'go'
    #     output-file-path: new-benchmarks.txt
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     auto-push: false
    #     save-data-file: true
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          let comment = '## 📊 Performance Benchmark Results\n\n';

          // Add comparison results if available
          if (fs.existsSync('comparison.txt')) {
            const comparison = fs.readFileSync('comparison.txt', 'utf8');
            comment += '### Comparison with main branch:\n```\n' + comparison + '\n```\n\n';
          } else {
            comment += 'Benchmark results available in artifacts.\n';
          }

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });